

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 8760e6d2a7e19913bc40675dd71f374bcd51b0ae

    - name: Run install.sh
      run: |
        ./install.sh
    - name: Run export.sh        
      run: . ./export.sh
    - name: Run build
      run: idf.py build
