

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 8760e6d2a7e19913bc40675dd71f374bcd51b0ae
    - name: Install dependencies
      run: | 
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
    - name: Run install.sh
      run: |
        ./install.sh all
    - name: Run export.sh        
      run: | 
        . ./export.sh
        cd /home/runner/work/esp-idf/esp-idf/examples
        ls
        cd ~/examples/get-started/hello_world
        idf.py set-target esp32
        idf.py menuconfig
        idf.py build
